int aGlobal; bool aGlobal;
a = 4;
3;
3 + 4;
int bGlobal + 4;
aGlobal = 4;
4 = 4;
int cGlobal = bogus;
Function dGlobal = void() ( 3 + int a;
	z;
	int b = (int)"hello";
	int fineOnLeft = int notFineOnRight;
	String.3;
	String.bogus;
	Main..bogus;
	Main.bogus;
	3 : 3;
	aGlobal.b;
	aGlobal..b;
	true && 4;
	!4;
	3 >> "hello";
	~"hello";
	3.5 * "hello";
	-"hello";
	3 + dGlobal;
	"hello" + dGlobal;
	dGlobal + 3;
	dGlobal + "hello";
	dGlobal + dGlobal;
	dGlobal ? dGlobal : dGlobal;
	dGlobal ? dGlobal;
	true ? 3 : "String";
	dGlobal = dGlobal = dGlobal;
	3 = 3;
	dGlobal = 3;
	3 == "String";
	3++;
	"String" > "String";
	3();
	Function c; c = void() (); c();
	dGlobal(3);
	Function d = int(int e) ( return e; ); d();
	d("hello");
	if (3) ;
	while (3) ; );
Function eGlobal = int() ();
Function fGlobal = int() ( return "hello"; );
Function gGlobal = void() ( (int a = 4) == 4 && (int b = a) == 4; b = 6; );
Function hGlobal = void() ( (int a = 4) == 4 || (int b = a) == 4; b = 6; );
Function iGlobal = void() ( ((int a = 4) == 4 && (int b = a) == 4) || (int c = b) == 4; );
Function jGlobal = void() ( ((int a = 4) == 4 || (int b = a) == 4) && (int c = b) == 4; );
Function kGlobal = void() ( true ? (int a = 4) : a; );
Function lGlobal = void() ( true ? a : (int a = 4); );
Function mGlobal = void() ( if (true) int a = 4; a = 3; );
Function nGlobal = void() ( if (false) ; else int a = 4; a = 3; );
Function oGlobal = void() ( if ((int a = 4) == 4 && (int b = a) == 5) ; else b = 3; );
Function pGlobal = void() ( if ((int a = 4) == 4 && (int b = a) == 5) ; b = 3; );
Function qGlobal = void() ( if ((int a = 4) == 4 || (int b = a) == 5) b = 3; );
Function rGlobal = void() ( if ((int a = 4) == 4 || (int b = a) == 5) ; b = 3; );
Function sGlobal = void() ( if ((int a = 4) == 5) return; else if ((int b = a) == 6) return; b = 3; );
Function tGlobal = void() ( if (true) int a = 4; else return; a = 3; );
Function uGlobal = void() ( if (false) return; else int a = 4; a = 3; );
Function vGlobal = void() ( for (int a = 0; false;) ; a = 4; );
Function wGlobal = void() ( for (; false;) int a = 0; a = 4; );
Function xGlobal = void() ( for (; (bool a = true); a = true) ; );
Function yGlobal = void() ( for (; (bool a = true); ) a = true; );
Function zGlobal = void() ( for (; (bool a = true); ) ; a = true; );
Function aaGlobal = void() ( for (; a == 3; (int a = 4)) ;);
Function abGlobal = void() ( for (; false; (int a = 4)) a = 4;);
Function acGlobal = void() ( for (; false; (int a = 4)) ; a = 4; );
Function adGlobal = void() ( bool a = (bool)dGlobal(); );
Function aeGlobal = int() ( return; );
